---
booktitle: Proceedings of the Open Algorithm Selection Challenge
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
shortname: OASC
year: '2017'
volume: 79
published: 2017-12-21
start: 2017-09-11
end: 2017-09-12
url: https://proceedings.mlr.press
author:
  name: PMLR
layout: proceedings
publisher: PMLR
series: Proceedings of Machine Learning Research
issn: 2640-3498
id: OASC
month: 0
cycles: false
editor:
- given: Marius
  family: Lindauer
- given: Jan N.
  family: van Rijn
- given: Lars
  family: Kotthoff
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Open Algorithm Selection Challenge
    Held in Brussels, Belgium on 11-12 September 2017

  Published as Volume 79 by the Proceedings of Machine Learning Research on 21 December 2017.

  Volume Edited by:
    Marius Lindauer
    Jan N. van Rijn
    Lars Kotthoff

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 11--12 Sep
baseurl: "/v79"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v79
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: Open Algorithm Selection Challenge 2017
  url: 
  location: Brussels, Belgium
  dates:
  - 2017-09-11
  - 2017-09-12
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
